---

# - name: get facts from the swarm workers
#   setup:
#   - debug: var=allfacts

- name: Init the Docker Swarm Nodes
  docker_swarm:
    state: join
    tls: yes
    # advertise_addr: 
      # should be detected automatically
    join_token: "{{ docker_swarm_manager.JoinTokens.Worker }}"
    remote_addrs: 
      - "{{ gce_manager_ip.address }}:2377"
