---

# Remove resources

- name: Destroy all resources
  hosts: local
  gather_facts: False
  vars_files:
    - gce_vars/auth
    - gce_vars/machines
    - gce_vars/zone
  tasks:
    - name: destroy the instance group
      gcp_compute_instance_group:
        name: "instancegroup-globalforwardingrule"
        zone: "{{zone}}"
        project: "{{ project }}"
        auth_kind: "{{ auth_kind }}"
        service_account_file: "{{ credentials_file }}"
        state: absent
      register: instancegroup
    - name: destroy the health check
      gcp_compute_http_health_check:
        name: "httphealthcheck-globalforwardingrule"
        project: "{{ project }}"
        auth_kind: "{{ auth_kind }}"
        service_account_file: "{{ credentials_file }}"
        state: absent
      register: healthcheck
    - name: destroy the backend service
      gcp_compute_backend_service:
        name: "backendservice-globalforwardingrule"
        project: "{{ project }}"
        auth_kind: "{{ auth_kind }}"
        service_account_file: "{{ credentials_file }}"
        health_checks: 
          - "{{ healthcheck.selfLink }}"
        backends:
          - group: "{{ instancegroup.selfLink }}"
        state: absent
      register: backendservice
    - name: destroy the url map
      gcp_compute_url_map:
        name: "urlmap-globalforwardingrule"
        default_service: "{{ backendservice }}"
        project: "{{ project }}"
        auth_kind: "{{ auth_kind }}"
        service_account_file: "{{ credentials_file }}"
        state: absent
      register: urlmap
    - name: destroy the target http proxy
      gcp_compute_target_http_proxy:
        name: "targethttpproxy-globalforwardingrule"
        url_map: " {{ urlmap }} "
        project: "{{ project }}"
        auth_kind: "{{ auth_kind }}"
        service_account_file: "{{ credentials_file }}"
        state: absent
      register: httpproxy
    - name: destroy the global forwarding rule
      gcp_compute_global_forwarding_rule:
        name: "globalfowardingrule"
        project: "{{ project }}"
        auth_kind: "{{ auth_kind }}"
        service_account_file: "{{ credentials_file }}"
        target: "{{ httpproxy.selfLink }}"
        state: absent
    - name: Delete the first instance
      gcp_compute_instance:
        name: "{{ name_zonea }}"
        zone: "{{ zone }}"
        project: "{{ project }}"
        service_account_file: "{{ credentials_file }}"
        auth_kind: "{{ auth_kind }}"
        state: absent
    - name: Delete the first address
      gcp_compute_address:
        name: "{{ name_zonea }}-ip"
        region: "{{ region }}"
        project: "{{ project }}"
        service_account_file: "{{ credentials_file }}"
        auth_kind: "{{ auth_kind }}"
        state: absent
    - name: Delete the second instance
      gcp_compute_instance:
        name: "{{ name_zoneb }}"
        zone: "{{ zone }}"
        project: "{{ project }}"
        service_account_file: "{{ credentials_file }}"
        auth_kind: "{{ auth_kind }}"
        state: absent
    - name: Delete the second address
      gcp_compute_address:
        name: "{{ name_zoneb }}-ip"
        region: "{{ region }}"
        project: "{{ project }}"
        service_account_file: "{{ credentials_file }}"
        auth_kind: "{{ auth_kind }}"
        state: absent
