---
- name: Install Docker on the instances
  hosts: gce_instances_ips
  become: yes
  become_method: sudo
  roles:
    - infrastructure
- name: Configure Docker Swarm Manager
  hosts: docker_manager
  become: yes
  become_method: sudo
  roles:
    - docker_manager
- name: Configure Swarm Nodes
  hosts: docker_nodes
  become: yes
  become_method: sudo
  roles:
    - docker_nodes