---
- name: Install Docker on the instances
  hosts: gce_instances_ips
  gather_facts: False
  become: yes
  become_method: sudo
  roles:
    - infrastructure
- name: Configure Docker Swarm Manager
  gather_facts: False
  hosts: managers
  become: yes
  become_method: sudo
  roles:
    - docker_managers_role
- name: Configure Swarm Nodes
  gather_facts: False
  hosts: nodes
  become: yes
  become_method: sudo
  roles:
    - docker_nodes_role