---
- name: Install Docker on the instances
  hosts: gce_instances_ips
  gather_facts: False
  become: yes
  become_method: sudo
  roles:
    - infrastructure
- name: Configure Docker Swarm Manager
  hosts: docker_managers
  become: yes
  become_method: sudo
  roles:
    - docker_managers_role
- name: Configure Swarm Nodes
  hosts: docker_nodes
  become: yes
  become_method: sudo
  roles:
    - docker_nodes_role