---
- name: Install Docker on the instances
  hosts: gce_instances_ips
  gather_facts: False
  vars_files:
    - gce_vars/auth
    - gce_vars/machines
    - gce_vars/zone
  become: yes
  become_method: sudo
  roles:
    - infrastructure
- name: Configure Docker Swarm Manager
  hosts: docker_managers_ips
  gather_facts: False
  vars_files:
    - gce_vars/auth
    - gce_vars/machines
    - gce_vars/zone
  become: yes
  become_method: sudo
  roles:
    - docker_managers_role
- name: Configure Swarm Nodes
  hosts: docker_nodes_ips
  gather_facts: False
  vars_files:
    - gce_vars/auth
    - gce_vars/machines
    - gce_vars/zone
  become: yes
  become_method: sudo
  roles:
    - docker_nodes_role