---
- name: Add yum package yum-utils
  yum: 
    name: yum-utils
    state: latest 

- name: Add yum docker repo
  command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

- name: Install docker
  # Can't use the 'yum' Ansible module in this case as it will install
  # default Docker version (19.x). Its requirement is to install 
  # containerd.io >= 2:2x which can't be fulfilled. '--nobest' option
  # lets install latest Docker that dependencies can be met.
  command: yum install -y docker-ce docker-ce-cli containerd.io --nobest

# - name: Install containerd.io
#   yum: 
#     name: containerd.io
#     state: latest
#     enablerepo: docker-ce-test

# - name: Install docker-ce
#   yum:
#     name: docker-ce
#     state: latest

# - name: Install docker-ce-cli
#   yum: 
#     name: docker-ce-cli
#     state: latest

- name: Deploy custom docker.service file
  copy: src=docker.service dest=/usr/lib/systemd/system/docker.service
        owner=root group=root mode=0644

- name: Start docker service
  systemd:
    daemon_reload: yes
    name: docker 
    state: restarted
    enabled: yes

# - name: Check docker version
#   command: docker version

# - name: Set file stats on index.html
#   file: path=/var/www/html/index.html owner=root group=root mode=0644

# - name: Enable mod_headers
#   file: path=/etc/apache2/mods-enabled/headers.load
#         src=/etc/apache2/mods-available/headers.load state=link

# - name: Re-start apache
#   service: name=apache2 state=restarted
