---

- debug: var=hostvars['localhost'].gce_manager
- name: Init the Docker Swarm Nodes
  docker_swarm:
    state: join
    tls: yes
    advertise_addr: eth0
    join_token: "{{ hostvars[groups['docker_managers_ips'][0]].ready_swarm_manager.swarm_facts.JoinTokens.Worker }}"
    remote_addrs: 
      - "{{ hostvars['localhost'].gce_manager.networkInterfaces.networkIP }}:2377"
