---

- name: Init a new swarm with default parameters
  docker_swarm:
    state: present
    tls: yes
  register: ready_swarm_manager
# - debug: var=ready_swarm_manager
- name: Export Swarm Workers token
  set_fact:
    cacheable: yes
    swarm_worker_token: "{{ ready_swarm_manager.swarm_facts.JoinTokens.Worker }}"
# - debug: var=swarm_worker_token
# - debug: var=hostvars[inventory_hostname]