name: Destroy

on:
  # workflow_dispatch
  push:
    branches: [ master ]

env:
  GCP_CREDENTIALS_FILE: ${{ secrets.GCP_CREDENTIALS_FILE }}
  GCP_SSH_KEY_FOR_ANSIBLE: ${{ secrets.GCP_SSH_KEY_FOR_ANSIBLE }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  destroy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Destroy GCP resources
        run: |
          echo $GCP_CREDENTIALS_FILE | base64 -d > gcp_credentials_file.json
          echo $GCP_SSH_KEY_FOR_ANSIBLE | base64 -d > gcp_ssh_key_for_ansible
          export ANSIBLE_HOST_KEY_CHECKING=False
          sudo apt update
          sudo apt install python3-google-auth
          ansible-playbook -i ansible_hosts cleanup.yml
            