# This is a basic workflow to help you get started with Actions

name: Create

on:
  # workflow_dispatch
  push:
    branches: [ master ]
  
env:
  GCP_CREDENTIALS_FILE: ${{ secrets.GCP_CREDENTIALS_FILE }}
  GCP_SSH_KEY_FOR_ANSIBLE: ${{ secrets.GCP_SSH_KEY_FOR_ANSIBLE }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  linter:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Ansible linter check
        run: |
          pip3 install ansible-lint
          ansible-lint

  build:
    runs-on: ubuntu-18.04
    needs: linter
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Install and run Ansible
        run: |
          echo $GCP_CREDENTIALS_FILE | base64 -d > gcp_credentials_file.json
          echo $GCP_SSH_KEY_FOR_ANSIBLE | base64 -d > gcp_ssh_key_for_ansible
          chmod 400 gcp_ssh_key_for_ansible
          export ANSIBLE_HOST_KEY_CHECKING=False
          sudo apt update
          sudo apt install python3-google-auth
          ansible-playbook -vi ansible_hosts gce-infrastructure-and-docker-deployment.yml